server:
  port: 8181
spring:
  datasource:
    username: root
    password: 171024
    url: jdbc:mysql://120.26.176.118:3306/bsp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  type-aliases-package: com.neusoft.bsp.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


